http:
  routers:
    menu-ws:
      rule: "PathPrefix(`/gs`)"
      service: menu-service
      entryPoints:
        - web
    menu-api:
      rule: "PathPrefix(`/api`)"
      service: menu-service
      entryPoints:
        - web
  services:
    menu-service:
      loadBalancer:
        servers:
          - url: "http://app1:8080"
          - url: "http://192.168.1.52:8080"
