version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"      # AMQP порт для обычных соединений
      - "15672:15672"    # Порт для RabbitMQ Management UI
      - "61613:61613"    # Порт для STOMP
    command: >
      bash -c "rabbitmq-plugins enable --offline rabbitmq_stomp &&
               rabbitmq-plugins enable --offline rabbitmq_web_stomp &&
               rabbitmq-server"
